version: "3.5"
services:
  postgres:
    image: postgres
    volumes:
      - "./data/postgres:/var/lib/postgresql/data/pgdata"
    environment:
      POSTGRES_USER: someone
      POSTGRES_PASSWORD: very_strong_password
      PGDATA: "/var/lib/postgresql/data/pgdata"

  app:
    build: .
    depends_on:
      - postgres
    ports:
      - 8000:8000
