version: "3.8"
services:
  postgres:
    image: postgres
    volumes:
      - "./data/postgres:/var/lib/postgresql/data/pgdata"
    environment:
      POSTGRES_USER: django_admin
      POSTGRES_PASSWORD: 1234
      PGDATA: "/var/lib/postgresql/data/pgdata"

  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - postgres
    ports:
      - 8000:8000
